apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mysql-rollout
  namespace: default
spec:
  replicas: {{ .Values.mysql-app.replicaCount }}
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 60s
      - setWeight: 100
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql-app
          image: "{{ .Values.mysql-app.image.repository }}:{{ .Values.mysql-app.image.tag }}"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: 'yes'
            - name: MYSQL_DATABASE
              value: semaphore
            - name: MYSQL_USER
              value: semaphore
            - name: MYSQL_PASSWORD
              value: semaphore
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard # Added StorageClass

