apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
        - name: semaphore
          image: semaphoreui/semaphore:latest
          ports:
            - containerPort: 3000
          env:
            - name: SEMAPHORE_DB_USER
              value: semaphore
            - name: SEMAPHORE_DB_PASS
              value: semaphore
            - name: SEMAPHORE_DB_HOST
              value: postgresql-service
            - name: SEMAPHORE_DB_PORT
              value: "5432"
            - name: SEMAPHORE_DB_DIALECT
              value: postgres
            - name: SEMAPHORE_DB
              value: semaphore
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: /tmp/semaphore/
            - name: SEMAPHORE_ADMIN_PASSWORD
              value: admin
            - name: SEMAPHORE_ADMIN_NAME
              value: admin
            - name: SEMAPHORE_ADMIN_EMAIL
              value: a.j.s-engineer@outlook.com
            - name: SEMAPHORE_ADMIN
              value: admin
            - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
              value: LxLP2zsSptao27pM6dTel83d5vdJOIydmktnHPrLkJU=
            - name: SEMAPHORE_LDAP_ACTIVATED
              value: 'no'
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"

---
apiVersion: v1
kind: Service
metadata:
  name: semaphore-service
spec:
  selector:
    app: semaphore
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: semaphore
            - name: POSTGRES_USER
              value: semaphore
            - name: POSTGRES_PASSWORD
              value: semaphore
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
