apiVersion: v1
kind: Service
metadata:
  name: semaphore-service
  namespace: default
spec:
  type: LoadBalancer 
  selector:
    app: semaphore-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


