{{- if .Values.blazor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.blazor.service.name }}
  labels:
    app: blazor-app
spec:
  type: {{ .Values.blazor.service.type }}
  ports:
  - port: {{ .Values.blazor.service.port }}
    targetPort: {{ .Values.blazor.service.port }}
    protocol: TCP
    name: http
  selector:
    app: blazor-app
{{- end }}
