apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dms-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dms.ajs-engineer.com  # Custom domain for local accesaaas
      http:
        paths:
          - path:
            pathType: Prefix
            backend:
              service:
                name: dms-service  # The service you've already set up
                port:
                  number: 80
