apiVersion: v1
kind: Service
metadata:
  name: dms-service
  namespace: default
spec:
  type: ClusterIP  # Internal routing via Istio
  selector:
    app: dms-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8282

