apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-app
  template:
    metadata:
      labels:
        app: cloudflare-app
    spec:
      containers:
        - name: cloudflare-app
          image: cloudflare/cloudflared:2024.3.0  # Pin to a specific version
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - "$(TUNNEL_TOKEN)"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-token
                  key: token
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
            requests:
              cpu: "250m"
              memory: "100Mi"

