apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-app
  
  template:
    metadata:
      labels:
        app: cloudflare-app
    spec:
      containers:
        - name: cloudflare-app
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - "eyJhIjoiZmE4MmRlMGFjNWE5Njg2YWIwNDZkMzVkMDdhMzQ2MDciLCJ0IjoiYzdlZTU1MWUtYjM2OS00MWZiLWI3MGMtNTFmMzAxNmRjMjI3IiwicyI6Ik9HTTNaREkxWldJdE1XSXpaUzAwTUdNM0xXRXdNV1l0TkdZNE1EUTJPV0V6TlRJNSJ9"
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"

