apiVersion: apps/v1
kind: Deployment
metadata:
  name: micros
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
        - name: microservice-container
          image: docker.io/ajaff/microservices:v1.0  # Ensure image exists in the registry
          ports:
            - containerPort: 3535
            - containerPort: 3536
            - containerPort: 3537
            - containerPort: 3538

---
apiVersion: v1
kind: Service
metadata:
  name: microservices-service
  namespace: default
spec:
  selector:
    app: microservices
  ports:
    - name: server1-port
      protocol: TCP
      port: 3535
      targetPort: 3535
    - name: server2-port
      protocol: TCP
      port: 3536
      targetPort: 3536
    - name: server3-port
      protocol: TCP
      port: 3537
      targetPort: 3537
    - name: server4-port
      protocol: TCP
      port: 3538
      targetPort: 3538
  type: LoadBalancer  # Use LoadBalancer or NodePort for external access

