apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodex
  namespace: default  # Ensure this is the correct namespace
spec:
  selector:
    matchLabels:
      app: nodex
  template:
    metadata:
      labels:
        app: nodex
    spec:
      hostNetwork: true  # Ensure the Pod uses the host's network (needed for Node Exporter)
      containers:
      - name: nodex
        image: prom/node-exporter:latest  # Latest version (you can specify a version if needed)
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      tolerations:
      - key: "node-role.kubernetes.io/master"  # Allow running on master nodes if needed
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: nodex
  namespace: default  # Ensure this matches the DaemonSet namespace
spec:
  type: NodePort  # Expose it as NodePort so it's accessible outside the cluster
  selector:
    app: nodex
  ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    nodePort: 30600  # Static nodePort, ensure it doesn't conflict with others

