apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmqx
  namespace: default
  labels:
    app: rabbitmqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmqx
  template:
    metadata:
      labels:
        app: rabbitmqx
    spec:
      containers:
        - name: rabbitmqx
          image: kbudde/rabbitmq-exporter:latest
          ports:
            - containerPort: 9419
          env:
            - name: RABBIT_URL
              value: "http://rabbitmq-service:15672"
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmqx-service
  namespace: default
spec:
  selector:
    app: rabbitmqx
  ports:
    - port: 9419
      targetPort: 9419
  type: LoadBalancer

