apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: hp-pvc
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
